[tool.poetry]
name = "pyrop-lint"
description = "Linting for pyrop"
version = "1.0.0"
authors = ["Nick DeRobertis <derobertis.nick@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9"
pyrop = {path = "../..", develop = true}
flake8 = "*"
mypy = "*"