
name: Run PR lint/format checks and tests
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ]
        python-version: ["3.8", "3.9", "3.10", ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-dependencies
      with:
        python-version: ${{ matrix.python-version }}
    # TODO: Check test coverage
    - uses: ./.github/actions/lint-and-test